int sys_setup(){return 0;}
int sys_exit(){return 0;}
int sys_fork(){return 0;}
int sys_read(){return 0;}
int sys_write(){return 0;}
int sys_open(){return 0;}
int sys_close(){return 0;}
int sys_waitpid(){return 0;}
int sys_creat(){return 0;}
int sys_link(){return 0;}
int sys_unlink(){return 0;}
int sys_execve(){return 0;}
int sys_chdir(){return 0;}
int sys_time(){return 0;}
int sys_mknod(){return 0;}
int sys_chmod(){return 0;}
int sys_chown(){return 0;}
int sys_break(){return 0;}
int sys_stat(){return 0;}
int sys_lseek(){return 0;}
int sys_getpid(){return 0;}
int sys_mount(){return 0;}
int sys_umount(){return 0;}
int sys_setuid(){return 0;}
int sys_getuid(){return 0;}
int sys_stime(){return 0;}
int sys_ptrace(){return 0;}
int sys_alarm(){return 0;}
int sys_fstat(){return 0;}
int sys_pause(){return 0;}
int sys_utime(){return 0;}
int sys_stty(){return 0;}
int sys_gtty(){return 0;}
int sys_access(){return 0;}
int sys_nice(){return 0;}
int sys_ftime(){return 0;}
int sys_sync(){return 0;}
int sys_kill(){return 0;}
int sys_rename(){return 0;}
int sys_mkdir(){return 0;}
int sys_rmdir(){return 0;}
int sys_dup(){return 0;}
int sys_pipe(){return 0;}
int sys_times(){return 0;}
int sys_prof(){return 0;}
int sys_brk(){return 0;}
int sys_setgid(){return 0;}
int sys_getgid(){return 0;}
int sys_signal(){return 0;}
int sys_geteuid(){return 0;}
int sys_getegid(){return 0;}
int sys_acct(){return 0;}
int sys_phys(){return 0;}
int sys_lock(){return 0;}
int sys_ioctl(){return 0;}
int sys_fcntl(){return 0;}
int sys_mpx(){return 0;}
int sys_setpgid(){return 0;}
int sys_ulimit(){return 0;}
int sys_uname(){return 0;}
int sys_umask(){return 0;}
int sys_chroot(){return 0;}
int sys_ustat(){return 0;}
int sys_dup2(){return 0;}
int sys_getppid(){return 0;}
int sys_getpgrp(){return 0;}
int sys_setsid(){return 0;}
int sys_sigaction(){return 0;}
int sys_sgetmask(){return 0;}
int sys_ssetmask(){return 0;}
int sys_setreuid(){return 0;}
int sys_setregid(){return 0;}
